sudo: false
language: node_js
node_js:
  - '4.6.2'

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

before_script:
  - cd ./blimflix
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - bower install
  - sleep 1 # give server time to start

script:
  - npm test
